version: '3.9'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    env_file:
      - ./configs/production.env
    networks:
      - elastic-net
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.2
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic-net
    depends_on:
      - elasticsearch
networks:
  elastic-net:
    driver: bridge
